# Generated by Django 2.0.5 on 2018-05-31 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MindNavigator_Server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='unnamed', max_length=128)),
                ('stressLevel', models.PositiveSmallIntegerField()),
                ('startTime', models.BigIntegerField()),
                ('endTime', models.BigIntegerField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MindNavigator_Server.User')),
            ],
        ),
    ]
