# Generated by Django 2.0.5 on 2018-05-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindNavigator_Server', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
    ]
