# Generated by Django 2.0.5 on 2018-05-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindNavigator_Server', '0003_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='interventionType',
            field=models.CharField(default='system', max_length=6),
        ),
    ]
