# Generated by Django 2.0.5 on 2018-05-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MindNavigator_Server', '0004_intervention_interventiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='interventionType',
            field=models.CharField(max_length=6),
        ),
    ]
